import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    files: ["**/*.js"],
    ignores: ["js/node_modules/**", "assets/**", "dist/**"],
    languageOptions: {
      sourceType: "module",
      ecmaVersion: 2022,
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        caches: "readonly",
        self: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        URL: "readonly",
        AbortController: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        process: "readonly",
        requestAnimationFrame: "readonly",
        NodeFilter: "readonly",
        MutationObserver: "readonly",
        CustomEvent: "readonly",
        Response: "readonly",
        global: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        Event: "readonly",
        location: "readonly",
        clearInterval: "readonly",
        setInterval: "readonly",
        performance: "readonly",
        ResizeObserver: "readonly",
        api: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-case-declarations": "off",
    },
  },
];
